// 'use client';

// import { verify } from 'jsonwebtoken';
// import { useRouter } from 'next/navigation';
// import dbConnect from '@/lib/db';
// import User from '@/models/User';
// import { useEffect } from 'react';
// import { useAuth } from '@/contexts/AuthContext';
// import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
// import { FileText, Download, Calendar, DollarSign, TrendingUp } from 'lucide-react';
// import { Button } from '@/components/ui/button';


// export default async function EmployeeDashboardPage() {

//   const { user } = useAuth(); 
// const router = useRouter();

//   if (!user) {
//     router.push('/login');
//   }

//   useEffect(() => {
//     if (user?.role === 'ADMIN') {
//       router.push('/dashboard/admin');
//     }
//   }, [user]);

//   // const user = {
//   // name: 'John Doe',
//   // email: 'example@gmail.com',
//   // role: 'EMPLOYEE',
//   // status: 'ACTIVE',
//   // };

//   const stats = [
//     {
//       title: 'Current Month Salary',
//       value: '₹0.00',
//       description: 'Salary slip not generated yet',
//       icon: DollarSign,
//       color: 'text-green-600',
//       bgColor: 'bg-green-100 dark:bg-green-900',
//     },
//     {
//       title: 'Total Salary Slips',
//       value: '0',
//       description: 'All time generated',
//       icon: FileText,
//       color: 'text-blue-600',
//       bgColor: 'bg-blue-100 dark:bg-blue-900',
//     },
//     {
//       title: 'YTD Earnings',
//       value: '₹0.00',
//       description: 'Year to date total',
//       icon: TrendingUp,
//       color: 'text-purple-600',
//       bgColor: 'bg-purple-100 dark:bg-purple-900',
//     },
//     {
//       title: 'Last Payment',
//       value: 'N/A',
//       description: 'No payment history',
//       icon: Calendar,
//       color: 'text-orange-600',
//       bgColor: 'bg-orange-100 dark:bg-orange-900',
//     },
//   ];

//   return (
//     <div className="space-y-8">
//       {/* Header */}
//       <div>
//         <h1 className="text-3xl font-bold tracking-tight">Employee Dashboard</h1>
//         <p className="text-muted-foreground mt-2">
//           Welcome back, {user.name}! View your salary information and documents.
//         </p>
//       </div>

//       {/* Stats Grid */}
//       <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-4">
//         {stats.map((stat, index) => (
//           <Card key={index}>
//             <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
//               <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
//               <div className={`p-2 rounded-lg ${stat.bgColor}`}>
//                 <stat.icon className={`h-4 w-4 ${stat.color}`} />
//               </div>
//             </CardHeader>
//             <CardContent>
//               <div className="text-2xl font-bold">{stat.value}</div>
//               <p className="text-xs text-muted-foreground mt-1">{stat.description}</p>
//             </CardContent>
//           </Card>
//         ))}
//       </div>

//       {/* Quick Access */}
//       <div className="grid gap-4 md:grid-cols-2">
//         <Card>
//           <CardHeader>
//             <CardTitle>Quick Access</CardTitle>
//             <CardDescription>Access your documents quickly</CardDescription>
//           </CardHeader>
//           <CardContent className="space-y-2">
//             <Button variant="outline" className="w-full justify-start" asChild>
//               <a href="/dashboard/employee/salary-slips">
//                 <FileText className="mr-2 h-4 w-4" />
//                 View All Salary Slips
//               </a>
//             </Button>
//             <Button variant="outline" className="w-full justify-start" asChild>
//               <a href="/dashboard/employee/profile">
//                 <DollarSign className="mr-2 h-4 w-4" />
//                 View Profile
//               </a>
//             </Button>
//           </CardContent>
//         </Card>

//         <Card>
//           <CardHeader>
//             <CardTitle>Recent Salary Slips</CardTitle>
//             <CardDescription>Your latest payment documents</CardDescription>
//           </CardHeader>
//           <CardContent>
//             <div className="text-center py-8 text-muted-foreground">
//               <FileText className="mx-auto h-12 w-12 mb-2 opacity-50" />
//               <p className="text-sm">No salary slips generated yet</p>
//               <p className="text-xs mt-1">Your salary slips will appear here once generated by admin</p>
//             </div>
//           </CardContent>
//         </Card>
//       </div>

//       {/* Account Status */}
//       <Card>
//         <CardHeader>
//           <CardTitle>Account Information</CardTitle>
//           <CardDescription>Your account details and status</CardDescription>
//         </CardHeader>
//         <CardContent>
//           <div className="grid gap-4 md:grid-cols-2">
//             <div>
//               <label className="text-sm font-medium">Full Name</label>
//               <p className="text-sm text-muted-foreground mt-1">{user.name}</p>
//             </div>
//             <div>
//               <label className="text-sm font-medium">Email</label>
//               <p className="text-sm text-muted-foreground mt-1">{user.email}</p>
//             </div>
//             <div>
//               <label className="text-sm font-medium">Role</label>
//               <p className="text-sm text-muted-foreground mt-1">
//                 <span className="inline-flex items-center rounded-full bg-blue-100 dark:bg-blue-900 px-2 py-1 text-xs font-medium text-blue-700 dark:text-blue-300">
//                   {user.role}
//                 </span>
//               </p>
//             </div>
//             <div>
//               <label className="text-sm font-medium">Status</label>
//               <p className="text-sm text-muted-foreground mt-1">
                // <span className={`inline-flex items-center rounded-full px-2 py-1 text-xs font-medium ${
                //   user.status === 'ACTIVE' 
                //     ? 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300' 
                //     : 'bg-yellow-100 dark:bg-yellow-900 text-yellow-700 dark:text-yellow-300'
                // }`}>
                //   {user.status}
                // </span>

//               </p>
//             </div>
//           </div>
//         </CardContent>
//       </Card>
//     </div>
//   );
// }





'use client';

import { useEffect, useState } from 'react';
import { useAuth } from '@/contexts/AuthContext';
import { useRouter } from 'next/navigation';
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { Alert, AlertDescription } from '@/components/ui/alert';
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs';
import { Badge } from '@/components/ui/badge';
import { 
  FileText, 
  Download, 
  Calendar, 
  DollarSign, 
  TrendingUp, 
  User,
  Briefcase,
  Mail,
  Phone,
  MapPin,
  Building,
  CreditCard,
  FileCheck,
  Clock,
  Loader2,
  AlertCircle
} from 'lucide-react';

interface EmployeeData {
  employeeId: string;
  name: string;
  gender?: string;
  dob?: string;
  contact: {
    email: string;
    phone?: string;
    address?: string;
  };
  job: {
    department: string;
    designation: string;
    joinDate: string;
    employmentType: string;
    manager?: string;
  };
  salary: {
    basic: number;
    hra?: number;
    transportAllowances?: number;
    medicalAllowances?: number;
    bonus?: {
      title: string;
      amount: number;
    };
    deductions?: {
      pf?: number;
      tax?: number;
      other?: {
        title: string;
        amount: number;
      };
    };
    net: number;
  };
  bank?: {
    name: string;
    accountNumber: string;
    ifsc: string;
    upi?: string;
  };
  documents?: {
    pan?: string;
    aadhar?: string;
  };
  role: string;
  status: string;
}

interface SalarySlip {
  _id: string;
  month: string;
  year: number;
  grossSalary: number;
  netSalary: number;
  generatedAt: string;
}

export default function EmployeeDashboardPage() {
  const { user } = useAuth();
  const router = useRouter();
  
  // const [employeeData, setEmployeeData] = useState<EmployeeData as any>(null);
  const [employeeData, setEmployeeData] = useState<any>(null);
  const [salarySlips, setSalarySlips] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState('');
  const [activeTab, setActiveTab] = useState('overview');

  useEffect(() => {
    fetchEmployeeData();
  }, [user, router]);

  const fetchEmployeeData = async () => {
    try {
      setLoading(true);
      setError('');

      // Check localStorage first (valid for 8 hours)
      const cachedData = localStorage.getItem('employeeData');
      const cacheTimestamp = localStorage.getItem('employeeDataTimestamp');
      
      if (cachedData && cacheTimestamp) {
        const timestamp = parseInt(cacheTimestamp);
        const eightHoursInMs = 8 * 60 * 60 * 1000;

        if (Date.now() - timestamp < eightHoursInMs) {
          const parsed = JSON.parse(cachedData);
          setEmployeeData(parsed.employee);
          setSalarySlips(parsed.salarySlips || []);
          setLoading(false);
          return;
        }
      }

      // Fetch from API
      const response = await fetch('/api/employee/profile');
      
      if (!response.ok) {
        throw new Error('Failed to fetch employee data');
      }

      const data = await response.json();
      
      // Cache the data
      localStorage.setItem('employeeData', JSON.stringify(data));
      localStorage.setItem('employeeDataTimestamp', Date.now().toString());
      
      setEmployeeData(data.employee);
      setSalarySlips(data.salarySlips);
      console.log(data.salarySlips);
    } catch (err: any) {
      setError(err.message || 'Failed to load employee data');
    } finally {
      setLoading(false);
    }
  };

  const calculateYTDEarnings = () => {
    return salarySlips.reduce((total, slip) => total + slip.netSalary, 0);
  };

  const getLastPayment = () => {
    if (salarySlips.length === 0) return null;
    const lastSlip = salarySlips[0];
    return {
      amount: lastSlip.netSalary,
      date: new Date(lastSlip.generatedAt).toLocaleDateString('en-IN', { 
        month: 'short', 
        year: 'numeric' 
      })
    };
  };

  const downloadSalarySlip = async (slipId: string, month: string, year: number) => {
    try {
      const response = await fetch(`/api/employee/download/${slipId}`);
      // have to update this api after lunch 

      if (!response.ok) {
        throw Error('Failed to download salary slip');
      }

      const blob = await response.blob();
      const url = window.URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `salary-slip-${month}-${year}.pdf`;
      document.body.appendChild(a);
      a.click();
      window.URL.revokeObjectURL(url);
      document.body.removeChild(a);
    } catch (err) {
      console.error('Download error:', err);
    }
  };

  if (loading) {
    return (
      <div className="flex items-center justify-center min-h-[60vh]">
        <Loader2 className="h-8 w-8 animate-spin text-primary" />
      </div>
    );
  }

  if (error) {
    return (
      <Alert variant="destructive">
        <AlertCircle className="h-4 w-4" />
        <AlertDescription>{error}</AlertDescription>
      </Alert>
    );
  }

  if (!employeeData) {
    return null;
  }

  const currentMonthSlip = salarySlips[0]
  const lastPayment = getLastPayment();
  const ytdEarnings = calculateYTDEarnings();

  const stats = [
    {
      title: `${currentMonthSlip?.salary.month || 'Last' } Month Salary`,
      value: currentMonthSlip
        ? `₹${currentMonthSlip.salary.netSalary?.toLocaleString('en-IN')}` 
        : '₹0.00',
      description: currentMonthSlip 
        ? `${currentMonthSlip.salary.month} ${currentMonthSlip.salary.year}` 
        : 'Salary slip not generated yet',
      icon: DollarSign,
      color: 'text-green-600',
      bgColor: 'bg-green-100 dark:bg-green-900',
    },
    {
      title: 'Total Salary Slips',
      value: salarySlips.length.toString(),
      description: 'All time generated',
      icon: FileText,
      color: 'text-blue-600',
      bgColor: 'bg-blue-100 dark:bg-blue-900',
    },
    {
      title: 'YTD Earnings',
      value: `₹${ytdEarnings.toLocaleString('en-IN')}`,
      description: 'Year to date total',
      icon: TrendingUp,
      color: 'text-purple-600',
      bgColor: 'bg-purple-100 dark:bg-purple-900',
    },
    {
      title: 'Last Payment',
      value: lastPayment ? `₹${lastPayment.amount?.toLocaleString('en-IN')}` : 'N/A',
      description: lastPayment ? lastPayment.date : 'No payment history',
      icon: Calendar,
      color: 'text-orange-600',
      bgColor: 'bg-orange-100 dark:bg-orange-900',
    },
  ];

  return (
    <div className="space-y-6 p-4 md:p-6">
      {/* Header */}
      <div>
        <h1 className="text-2xl md:text-3xl font-bold tracking-tight">
          Employee Dashboard
        </h1>
        <p className="text-muted-foreground mt-2">
          Welcome back, {employeeData.name}!
        </p>
      </div>

      {/* Stats Grid */}
      <div className="grid gap-4 grid-cols-1 sm:grid-cols-2 lg:grid-cols-4">
        {stats.map((stat, index) => (
          <Card key={index}>
            <CardHeader className="flex flex-row items-center justify-between space-y-0 pb-2">
              <CardTitle className="text-sm font-medium">{stat.title}</CardTitle>
              <div className={`p-2 rounded-lg ${stat.bgColor}`}>
                <stat.icon className={`h-4 w-4 ${stat.color}`} />
              </div>
            </CardHeader>
            <CardContent>
              <div className="text-xl md:text-2xl font-bold">{stat.value}</div>
              <p className="text-xs text-muted-foreground mt-1">
                {stat.description}
              </p>
            </CardContent>
          </Card>
        ))}
      </div>

      {/* Main Content Tabs */}
      <Tabs value={activeTab} onValueChange={setActiveTab}>
        <TabsList className="grid h-24 md:h-10 w-full grid-cols-2 lg:grid-cols-4">
          <TabsTrigger value="overview">Overview</TabsTrigger>
          <TabsTrigger value="salary-slips">Salary Slips</TabsTrigger>
          <TabsTrigger value="profile">Profile</TabsTrigger>
          <TabsTrigger value="documents">Documents</TabsTrigger>
        </TabsList>

        {/* Overview Tab */}
        <TabsContent value="overview" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            {/* Current Month Salary Breakdown */}
            {currentMonthSlip && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <DollarSign className="h-5 w-5" />
                    {currentMonthSlip.salary.month} Month Breakdown
                  </CardTitle>
                  <CardDescription>
                    {currentMonthSlip.salary.month} {currentMonthSlip.salary.year}
                  </CardDescription>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div className="flex justify-between text-green-600 dark:text-green-400 ">
                    <span className="text-sm text-muted-foreground">Basic Salary</span>
                    <span className="font-medium">
                      ₹{currentMonthSlip.salary.basicSalary?.toLocaleString('en-IN')}
                    </span>
                  </div>
                  {currentMonthSlip.salary.allowances.hra && (
                    <div className="flex justify-between text-green-600 dark:text-green-400 ">
                      <span className="text-sm text-muted-foreground">HRA</span>
                      <span className="font-medium">
                        ₹{currentMonthSlip.salary.allowances.hra?.toLocaleString('en-IN')}
                      </span>
                    </div>
                  )}
                  {currentMonthSlip.salary.allowances.transport && (
                    <div className="flex justify-between text-green-600 dark:text-green-400">
                      <span className="text-sm text-muted-foreground">Transport</span>
                      <span className="font-medium">
                        ₹{currentMonthSlip.salary.allowances.transport?.toLocaleString('en-IN')}
                      </span>
                    </div>
                  )}
                  {currentMonthSlip.salary.deductions.pf && (
                    <div className="flex justify-between text-red-600 dark:text-red-400">
                      <span className="text-sm">PF Deduction</span>
                      <span className="font-medium">
                        -₹{currentMonthSlip.salary.deductions.pf.toLocaleString('en-IN') || '69'}
                      </span>
                    </div>
                  )}
                  {currentMonthSlip.salary.deductions?.tax && (
                    <div className="flex justify-between text-red-600 dark:text-red-400">
                      <span className="text-sm">Tax Deduction</span>
                      <span className="font-medium">
                        -₹{currentMonthSlip.salary.deductions.tax.toLocaleString('en-IN')}
                      </span>
                    </div>
                  )}
                  {currentMonthSlip.salary.deductions?.other && (
                    <div className="flex justify-between text-red-600 dark:text-red-400">
                      <span className="text-sm">Other Deductions</span>
                      <span className="font-medium">
                        -₹{currentMonthSlip.salary.deductions.other.toLocaleString('en-IN')}
                      </span>
                    </div>
                  )}

                  <div className="pt-3 border-t flex justify-between">
                    <span className="font-semibold">Net Salary</span>
                    <span className="font-bold text-lg text-green-600 dark:text-green-400">
                      ₹{currentMonthSlip.salary.netSalary?.toLocaleString('en-IN')}
                    </span>
                  </div>
                  <Button 
                    className="w-full mt-4" 
                    onClick={() => downloadSalarySlip(
                      currentMonthSlip._id, 
                      currentMonthSlip.salary.month, 
                      currentMonthSlip.salary.year)}
                  >
                    <Download className="mr-2 h-4 w-4" />
                    Download Slip
                  </Button>
                </CardContent>
              </Card>
            )}

            {/* Recent Activity */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Clock className="h-5 w-5" />
                  Recent Salary Slips
                </CardTitle>
                <CardDescription>Last 5 generated slips</CardDescription>
              </CardHeader>
              <CardContent>
                {salarySlips.length === 0 ? (
                  <div className="text-center py-8 text-muted-foreground">
                    <FileText className="mx-auto h-12 w-12 mb-2 opacity-50" />
                    <p className="text-sm">No salary slips generated yet</p>
                  </div>
                ) : (
                  <div className="space-y-2">
                    {salarySlips.slice(0, 5).map((slip) => (
                      <div
                        key={slip._id}
                        className="flex items-center justify-between p-3 rounded-lg border hover:bg-accent transition-colors"
                      >
                        <div className="flex items-center gap-3">
                          <FileText className="h-4 w-4 text-muted-foreground" />
                          <div>
                            <p className="text-sm font-medium">
                              {slip.salary.month} {slip.salary.year}
                            </p>
                            <p className="text-xs text-muted-foreground">
                              ₹{slip.salary.netSalary?.toLocaleString('en-IN')}
                            </p>
                          </div>
                        </div>
                        <Button
                          size="sm"
                          variant="ghost"
                          onClick={() => downloadSalarySlip(
                            slip._id, 
                            slip.salary.month, 
                            slip.salary.year
                          )}
                        >
                          <Download className="h-4 w-4" />
                        </Button>
                      </div>
                    ))}
                  </div>
                )}
              </CardContent>
            </Card>
          </div>
        </TabsContent>

        {/* Salary Slips Tab */}
        <TabsContent value="salary-slips" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle>All Salary Slips</CardTitle>
              <CardDescription>
                View and download your salary slips
              </CardDescription>
            </CardHeader>
            <CardContent>
              {salarySlips.length === 0 ? (
                <div className="text-center py-12 text-muted-foreground">
                  <FileText className="mx-auto h-16 w-16 mb-4 opacity-50" />
                  <p className="text-lg font-medium">No salary slips available</p>
                  <p className="text-sm mt-2">
                    Your salary slips will appear here once generated by admin
                  </p>
                </div>
              ) : (
                <div className="space-y-2">
                  {salarySlips.map((slip) => (
                    <div
                      key={slip._id}
                      className="flex flex-col sm:flex-row sm:items-center justify-between p-4 rounded-lg border hover:bg-accent transition-colors gap-3"
                    >
                      <div className="flex items-center gap-4">
                        <div className="p-2 rounded-lg bg-primary/10">
                          <FileText className="h-5 w-5 text-primary" />
                        </div>
                        <div>
                          <p className="font-medium">
                            {slip.salary.month} {slip.salary.year}
                          </p>
                          <p className="text-sm text-muted-foreground">
                            Generated on{' '}
                            {new Date(slip.createdAt).toLocaleDateString('en-IN')}
                          </p>
                        </div>
                      </div>
                      <div className="flex items-center gap-4">
                        <div className="text-right">
                          <p className="text-sm text-muted-foreground">Net Salary</p>
                          <p className="font-bold text-lg">
                            ₹{slip.salary.netSalary?.toLocaleString('en-IN') || 'N/A'}
                          </p>
                        </div>
                        <Button
                          size="sm"
                          onClick={() => downloadSalarySlip(
                            slip._id, 
                            slip.salary.month, 
                            slip.salary.year
                          )}
                        >
                          <Download className="mr-2 h-4 w-4" />
                          Download
                        </Button>
                      </div>
                    </div>
                  ))}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>

        {/* Profile Tab */}
        <TabsContent value="profile" className="space-y-4">
          <div className="grid gap-4 md:grid-cols-2">
            {/* Personal Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <User className="h-5 w-5" />
                  Personal Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Employee ID
                  </label>
                  <p className="font-medium">{employeeData.employeeId}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Full Name
                  </label>
                  <p className="font-medium">{employeeData.name}</p>
                </div>
                {employeeData.gender && (
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Gender
                    </label>
                    <p className="font-medium">{employeeData.gender}</p>
                  </div>
                )}
                {employeeData.dob && (
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Date of Birth
                    </label>
                    <p className="font-medium">
                      {new Date(employeeData.dob).toLocaleDateString('en-IN')}
                    </p>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Contact Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Mail className="h-5 w-5" />
                  Contact Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div className="flex items-start gap-2">
                  <Mail className="h-4 w-4 mt-1 text-muted-foreground" />
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Email
                    </label>
                    <p className="font-medium break-all">{employeeData.contact?.email}</p>
                  </div>
                </div>
                {employeeData.contact?.phone && (
                  <div className="flex items-start gap-2">
                    <Phone className="h-4 w-4 mt-1 text-muted-foreground" />
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">
                        Phone
                      </label>
                      <p className="font-medium">{employeeData.contact?.phone}</p>
                    </div>
                  </div>
                )}
                {employeeData.contact?.address && (
                  <div className="flex items-start gap-2">
                    <MapPin className="h-4 w-4 mt-1 text-muted-foreground" />
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">
                        Address
                      </label>
                      <p className="font-medium">{employeeData.contact.address}</p>
                    </div>
                  </div>
                )}
              </CardContent>
            </Card>

            {/* Job Information */}
            <Card>
              <CardHeader>
                <CardTitle className="flex items-center gap-2">
                  <Briefcase className="h-5 w-5" />
                  Job Information
                </CardTitle>
              </CardHeader>
              <CardContent className="space-y-3">
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Department
                  </label>
                  <p className="font-medium">{employeeData.job.department}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Designation
                  </label>
                  <p className="font-medium">{employeeData.job.designation}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Employment Type
                  </label>
                  <p className="font-medium">{employeeData.job.employmentType}</p>
                </div>
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Join Date
                  </label>
                  <p className="font-medium">
                    {new Date(employeeData.job.joinDate).toLocaleDateString('en-IN')}
                  </p>
                </div>
                {employeeData.job.manager && (
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Manager ID
                    </label>
                    <p className="font-medium">{employeeData.job.manager}</p>
                  </div>
                )}
                <div>
                  <label className="text-sm font-medium text-muted-foreground">
                    Status
                  </label>
                  <div className="mt-1">
                    <Badge


                className={`${employeeData.status === 'ACTIVE' 
                        ? 'bg-green-100 dark:bg-green-900 text-green-700 dark:text-green-300' 
                        : 'bg-yellow-100 dark:bg-yellow-900 text-yellow-700 dark:text-yellow-300'
                      }`}
                      >
                      {employeeData.status}
                    </Badge>
                  </div>
                </div>
              </CardContent>
            </Card>

            {/* Bank Information */}
            {employeeData.bank && (
              <Card>
                <CardHeader>
                  <CardTitle className="flex items-center gap-2">
                    <CreditCard className="h-5 w-5" />
                    Bank Information
                  </CardTitle>
                </CardHeader>
                <CardContent className="space-y-3">
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Bank Name
                    </label>
                    <p className="font-medium">{employeeData.bank.name}</p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      Account Number
                    </label>
                    <p className="font-medium font-mono">
                      {employeeData.bank.accountNumber}
                    </p>
                  </div>
                  <div>
                    <label className="text-sm font-medium text-muted-foreground">
                      IFSC Code
                    </label>
                    <p className="font-medium font-mono">{employeeData.bank.ifsc}</p>
                  </div>
                  {employeeData.bank.upi && (
                    <div>
                      <label className="text-sm font-medium text-muted-foreground">
                        UPI ID
                      </label>
                      <p className="font-medium">{employeeData.bank.upi}</p>
                    </div>
                  )}
                </CardContent>
              </Card>
            )}
          </div>
        </TabsContent>

        {/* Documents Tab */}
        <TabsContent value="documents" className="space-y-4">
          <Card>
            <CardHeader>
              <CardTitle className="flex items-center gap-2">
                <FileCheck className="h-5 w-5" />
                Documents
              </CardTitle>
              <CardDescription>Your registered documents</CardDescription>
            </CardHeader>
            <CardContent>
              {!employeeData.documents || 
               (!employeeData.documents.pan && !employeeData.documents.aadhar) ? (
                <div className="text-center py-12 text-muted-foreground">
                  <FileCheck className="mx-auto h-16 w-16 mb-4 opacity-50" />
                  <p className="text-lg font-medium">No documents on file</p>
                  <p className="text-sm mt-2">
                    Contact admin to update your documents
                  </p>
                </div>
              ) : (
                <div className="grid gap-4 md:grid-cols-2">
                  {employeeData.documents.pan && (
                    <div className="p-4 rounded-lg border">
                      <div className="flex items-center gap-2 mb-2">
                        <FileText className="h-5 w-5 text-primary" />
                        <h3 className="font-semibold">PAN Card</h3>
                      </div>
                      <p className="text-sm text-muted-foreground">PAN Number</p>
                      <p className="font-mono font-medium text-lg">
                        {employeeData.documents.pan}
                      </p>
                    </div>
                  )}
                  {employeeData.documents.aadhar && (
                    <div className="p-4 rounded-lg border">
                      <div className="flex items-center gap-2 mb-2">
                        <FileText className="h-5 w-5 text-primary" />
                        <h3 className="font-semibold">Aadhar Card</h3>
                      </div>
                      <p className="text-sm text-muted-foreground">Aadhar Number</p>
                      <p className="font-mono font-medium text-lg">
                        {employeeData.documents.aadhar}
                      </p>
                    </div>
                  )}
                </div>
              )}
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  );
}